* Molecular Dynamics Simulation
** Introduction
This project implements a *Molecular Dynamics (MD)* simulation using the Lennard-Jones potential to model interactions between particles. It includes *periodic boundary conditions* (PBCs), *cutoff radius optimizations*, and integrates *Velocity Verlet* for time evolution. A CSV and PDB output are produced in the out directory.

The project is compiled using *Ninja and CMake* so compilation goes brrrrrrrrr.

*/!\ For educational purposes only. Some elements may be visually disturbing, and exposure to certain code may cause irreversible eye damage. /!\*

** Build instructions
Requirements are in the CMakeLists.txt. You can chose the configuration you want.

#+begin_src bash
mkdir build
cmake --build .. --config Release # -O3 -march=native
cmake --build .. --config Debug   # -O0
#+end_src

Then just ninja it.

#+begin_src bash
# In the build directory
ninja
#+end_src

You can also plot Temperature and kinetic energy. The command will create an png plot file.

#+begin_src bash
gnuplot script/plot_data.gnu
#+end_src

** Usage
#+begin_src bash
Usage: ./simulation [options]
Options:
  -n, --steps <value>        Number of time steps (default: 1000)
  -dt, --timestep <value>    Time step size (default: 1)
  -T, --temperature <value>  Target temperature (default: 300)
  -i, --input <file>         Input file with initial particle positions (default: ../input/particule.xyz)
  -o, --output <file>        Output file for results (default: ../out/output_data.csv)
                             Example for creating ../out/ex_output.csv and ./out/ex_output.pdb:
                             ./simulation -o ex_output
  -rc, --cutoff <value>      Cutoff distance for Lennard-Jones potential (default:10)
  -L, --boxsize <value>      Simulation box size (default: 42)
  -m, --mass <value>         Particle mass (default: 18)
  -tau, --relaxationtime <value>  Thermostat relaxation time (default: 3)
  -N, --particles <value>    Number of particles (default: 1000)
  -s, --seed <value>         Random seed (default: 420)
  -h, --help                 Display this help message
#+end_src

** Project organisation
#+begin_src bash
├── main.cpp
├── README.org
├── CMakeLists.txt
├── include
│   ├── parameters.h
│   ├── simulation.h
│   ├── types.h
│   └── utils.h
├── input
│   └── particule.xyz
├── out
│   ├── particules_data.csv
│   └── particules_data.pdb
├── script
│   ├── plot_data.gnu
└── src
    ├── simulation.cpp
    └── utils.cpp
#+end_src

* fo fer
- TODO Doxygen
- TODO Parralléliser le code
- TODO Correction de la fonction ~void compute_potential_energy(Particles& p, f64& U_total)~